source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
include:     ['.htaccess']
exclude:     ['rss', 'rss.xml']
keep_files:  ['.git','.svn']
timezone:    Europe/Budapest

future:      true
show_drafts: nil
limit_posts: 0
highliter: false

relative_permalinks: false
permalink: /:categories/:title
paginate_path: 'page:num'

markdown:      kramdown
markdown_ext:  markdown,mkd,mkdn,md
textile_ext:   textile

excerpt_separator: "\n\n"

safe:        false
host:        0.0.0.0
port:        4000
baseurl:     /
url:         http://localhost:4000
lsi:         false

# RSS
name: matic&middot;laze.hu
url: http://laze.hu
description: "LAZE vagyok, ez az oldalam. Itt tal&aacute;lod az &ouml;n&eacute;letrajzom, a referenci&aacute;im. Posztjaim szem&eacute;lyes v&eacute;lem&eacute;nyemet t&uuml;kr&ouml;zik."
author: laze
copyright: Creative Commons - Attribution-NonCommercial-ShareAlike 3.0 Unported

#maruku:
#  use_tex:    false
#  use_divs:   false
#  png_engine: blahtex
#  png_dir:    images/latex
#  png_url:    /images/latex
#
#rdiscount:
#  extensions: []
#
#redcarpet:
#  extensions: []
#
#kramdown:
#  auto_ids: true
#  footnote_nr: 1
#  entity_output: as_char
#  toc_levels: 1..6
#  smart_quotes: lsquo,rsquo,ldquo,rdquo
#  use_coderay: false
#
#  coderay:
#    coderay_wrap: div
#    coderay_line_numbers: inline
#    coderay_line_numbers_start: 1
#    coderay_tab_width: 4
#    coderay_bold_every: 10
#    coderay_css: style
#
#redcloth:
#  hard_breaks: true